### PR TITLE
Add support for `Linker` defined host functions

### PR DESCRIPTION
**Pull request by Robbepop**
Closes https://github.com/paritytech/wasmi/issues/663.

cc @flavio

## Todo

- [x] Add tests for `Linker::func_new` and `Linker::func_wrap`.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
## BENCHMARKS ## 

 <table> <thead> <tr> <th></th><th colspan=3>NATIVE</th><th colspan=3>WASMTIME</th><th></th> </tr> <tr> <th>BENCHMARK</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>WASMTIME OVERHEAD</th> </tr> </thead> <tbody> <tr><td><tt>execute/</tt><br><tt>bare_call_0</td> <td nowrap> 1.44ms</td> <td nowrap> 1.43ms</td> <td nowrap> :white_circle: -0.22%</td> <td nowrap> 1.08ms</td> <td nowrap> 1.06ms</td> <td nowrap> :red_circle: -1.40%</td> <td nowrap> :green_circle: -26%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_0/typed</td> <td nowrap> 1.02ms</td> <td nowrap> 1.02ms</td> <td nowrap> :white_circle: -0.26%</td> <td nowrap> 738.45µs</td> <td nowrap> 758.19µs</td> <td nowrap> :red_circle: 2.61%</td> <td nowrap> :green_circle: -26%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_1</td> <td nowrap> 1.49ms</td> <td nowrap> 1.49ms</td> <td nowrap> :red_circle: 0.05%</td> <td nowrap> 1.20ms</td> <td nowrap> 1.19ms</td> <td nowrap> :green_circle: -0.92%</td> <td nowrap> :green_circle: -20%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_16</td> <td nowrap> 2.31ms</td> <td nowrap> 2.43ms</td> <td nowrap> :red_circle: 4.84%</td> <td nowrap> 3.13ms</td> <td nowrap> 3.11ms</td> <td nowrap> :green_circle: -0.59%</td> <td nowrap> :green_circle: 28%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_16/typed</td> <td nowrap> 1.58ms</td> <td nowrap> 1.71ms</td> <td nowrap> :red_circle: 8.30%</td> <td nowrap> 1.52ms</td> <td nowrap> 1.38ms</td> <td nowrap> :green_circle: -9.14%</td> <td nowrap> :green_circle: -19%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_1/typed</td> <td nowrap> 1.14ms</td> <td nowrap> 1.15ms</td> <td nowrap> :white_circle: 0.62%</td> <td nowrap> 981.41µs</td> <td nowrap> 936.82µs</td> <td nowrap> :green_circle: -4.70%</td> <td nowrap> :green_circle: -18%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_4</td> <td nowrap> 1.56ms</td> <td nowrap> 1.59ms</td> <td nowrap> :red_circle: 1.15%</td> <td nowrap> 1.54ms</td> <td nowrap> 1.52ms</td> <td nowrap> :white_circle: -1.10%</td> <td nowrap> :green_circle: -4%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_4/typed</td> <td nowrap> 1.12ms</td> <td nowrap> 1.28ms</td> <td nowrap> :red_circle: 14.71%</td> <td nowrap> 1.03ms</td> <td nowrap> 1.03ms</td> <td nowrap> :white_circle: -0.03%</td> <td nowrap> :green_circle: -20%</td></tr><tr><td><tt>execute/</tt><br><tt>br_table</td> <td nowrap> 1.16ms</td> <td nowrap> 1.28ms</td> <td nowrap> :red_circle: 10.10%</td> <td nowrap> 1.18ms</td> <td nowrap> 1.12ms</td> <td nowrap> :green_circle: -5.47%</td> <td nowrap> :green_circle: -12%</td></tr><tr><td><tt>execute/</tt><br><tt>count_until</td> <td nowrap> 650.35µs</td> <td nowrap> 710.00µs</td> <td nowrap> :red_circle: 9.02%</td> <td nowrap> 1.21ms</td> <td nowrap> 1.15ms</td> <td nowrap> :green_circle: -4.86%</td> <td nowrap> :yellow_circle: 62%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial_iterative</td> <td nowrap> 321.64µs</td> <td nowrap> 326.54µs</td> <td nowrap> :red_circle: 1.63%</td> <td nowrap> 507.25µs</td> <td nowrap> 493.60µs</td> <td nowrap> :green_circle: -2.75%</td> <td nowrap> :yellow_circle: 51%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial_recursive</td> <td nowrap> 643.39µs</td> <td nowrap> 627.32µs</td> <td nowrap> :green_circle: -2.43%</td> <td nowrap> 1.10ms</td> <td nowrap> 1.09ms</td> <td nowrap> :white_circle: -0.68%</td> <td nowrap> :yellow_circle: 74%</td></tr><tr><td><tt>execute/</tt><br><tt>fib_iterative</td> <td nowrap> 1.46ms</td> <td nowrap> 1.46ms</td> <td nowrap> :white_circle: -0.11%</td> <td nowrap> 2.44ms</td> <td nowrap> 2.15ms</td> <td nowrap> :green_circle: -11.88%</td> <td nowrap> :green_circle: 47%</td></tr><tr><td><tt>execute/</tt><br><tt>fib_recursive</td> <td nowrap> 5.81ms</td> <td nowrap> 5.74ms</td> <td nowrap> :green_circle: -1.23%</td> <td nowrap> 9.65ms</td> <td nowrap> 9.69ms</td> <td nowrap> :white_circle: 0.34%</td> <td nowrap> :yellow_circle: 69%</td></tr><tr><td><tt>execute/</tt><br><tt>global_bump</td> <td nowrap> 1.18ms</td> <td nowrap> 1.01ms</td> <td nowrap> :green_circle: -14.35%</td> <td nowrap> 2.26ms</td> <td nowrap> 2.29ms</td> <td nowrap> :red_circle: 1.46%</td> <td nowrap> :red_circle: 127%</td></tr><tr><td><tt>execute/</tt><br><tt>global_const</td> <td nowrap> 686.21µs</td> <td nowrap> 798.91µs</td> <td nowrap> :red_circle: 16.36%</td> <td nowrap> 1.45ms</td> <td nowrap> 1.48ms</td> <td nowrap> :red_circle: 2.15%</td> <td nowrap> :yellow_circle: 86%</td></tr><tr><td><tt>execute/</tt><br><tt>host_calls</td> <td nowrap> 27.44µs</td> <td nowrap> 27.80µs</td> <td nowrap> :white_circle: 0.05%</td> <td nowrap> 38.43µs</td> <td nowrap> 37.68µs</td> <td nowrap> :green_circle: -1.90%</td> <td nowrap> :green_circle: 36%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_fill</td> <td nowrap> 1.20ms</td> <td nowrap> 1.33ms</td> <td nowrap> :red_circle: 11.00%</td> <td nowrap> 2.09ms</td> <td nowrap> 1.92ms</td> <td nowrap> :green_circle: -8.05%</td> <td nowrap> :green_circle: 44%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_sum</td> <td nowrap> 1.21ms</td> <td nowrap> 1.22ms</td> <td nowrap> :white_circle: 0.50%</td> <td nowrap> 2.12ms</td> <td nowrap> 1.95ms</td> <td nowrap> :green_circle: -7.93%</td> <td nowrap> :yellow_circle: 60%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_vec_add</td> <td nowrap> 2.39ms</td> <td nowrap> 2.47ms</td> <td nowrap> :red_circle: 3.65%</td> <td nowrap> 4.91ms</td> <td nowrap> 4.73ms</td> <td nowrap> :green_circle: -3.68%</td> <td nowrap> :yellow_circle: 91%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_is_even</td> <td nowrap> 1.15ms</td> <td nowrap> 1.16ms</td> <td nowrap> :white_circle: 1.33%</td> <td nowrap> 1.87ms</td> <td nowrap> 1.87ms</td> <td nowrap> :white_circle: 0.21%</td> <td nowrap> :yellow_circle: 61%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_ok</td> <td nowrap> 144.47µs</td> <td nowrap> 144.05µs</td> <td nowrap> :white_circle: -0.30%</td> <td nowrap> 261.51µs</td> <td nowrap> 256.39µs</td> <td nowrap> :green_circle: -1.99%</td> <td nowrap> :yellow_circle: 78%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_scan</td> <td nowrap> 176.97µs</td> <td nowrap> 175.96µs</td> <td nowrap> :white_circle: -0.68%</td> <td nowrap> 312.88µs</td> <td nowrap> 303.58µs</td> <td nowrap> :green_circle: -2.91%</td> <td nowrap> :yellow_circle: 73%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_trap</td> <td nowrap> 14.26µs</td> <td nowrap> 14.29µs</td> <td nowrap> :white_circle: -0.60%</td> <td nowrap> 26.06µs</td> <td nowrap> 25.43µs</td> <td nowrap> :green_circle: -2.35%</td> <td nowrap> :yellow_circle: 78%</td></tr><tr><td><tt>execute/</tt><br><tt>regex_redux</td> <td nowrap> 526.19µs</td> <td nowrap> 529.97µs</td> <td nowrap> :white_circle: 0.34%</td> <td nowrap> 997.52µs</td> <td nowrap> 986.48µs</td> <td nowrap> :white_circle: -1.07%</td> <td nowrap> :yellow_circle: 86%</td></tr><tr><td><tt>execute/</tt><br><tt>rev_complement</td> <td nowrap> 464.36µs</td> <td nowrap> 492.54µs</td> <td nowrap> :red_circle: 5.94%</td> <td nowrap> 838.22µs</td> <td nowrap> 805.28µs</td> <td nowrap> :green_circle: -3.87%</td> <td nowrap> :yellow_circle: 63%</td></tr><tr><td><tt>execute/</tt><br><tt>tiny_keccak</td> <td nowrap> 329.64µs</td> <td nowrap> 332.85µs</td> <td nowrap> :white_circle: 1.01%</td> <td nowrap> 641.34µs</td> <td nowrap> 625.17µs</td> <td nowrap> :green_circle: -2.51%</td> <td nowrap> :yellow_circle: 88%</td></tr><tr><td><tt>execute/</tt><br><tt>trunc_f2i</td> <td nowrap> 765.58µs</td> <td nowrap> 769.30µs</td> <td nowrap> :white_circle: 0.48%</td> <td nowrap> 1.44ms</td> <td nowrap> 1.48ms</td> <td nowrap> :red_circle: 2.91%</td> <td nowrap> :yellow_circle: 92%</td></tr><tr><td><tt>instantiate/</tt><br><tt>wasm_kernel</td> <td nowrap> 55.25µs</td> <td nowrap> 55.21µs</td> <td nowrap> :white_circle: 2.31%</td> <td nowrap> 59.85µs</td> <td nowrap> 55.20µs</td> <td nowrap> :green_circle: -8.47%</td> <td nowrap> :green_circle: -0%</td></tr><tr><td><tt>translate/</tt><br><tt>erc1155</td> <td nowrap> 233.51µs</td> <td nowrap> 234.26µs</td> <td nowrap> :white_circle: -0.27%</td> <td nowrap> 449.95µs</td> <td nowrap> 441.51µs</td> <td nowrap> :green_circle: -1.99%</td> <td nowrap> :yellow_circle: 88%</td></tr><tr><td><tt>translate/</tt><br><tt>erc20</td> <td nowrap> 112.96µs</td> <td nowrap> 113.48µs</td> <td nowrap> :white_circle: 0.45%</td> <td nowrap> 215.74µs</td> <td nowrap> 212.50µs</td> <td nowrap> :green_circle: -1.55%</td> <td nowrap> :yellow_circle: 87%</td></tr><tr><td><tt>translate/</tt><br><tt>erc721</td> <td nowrap> 165.56µs</td> <td nowrap> 161.31µs</td> <td nowrap> :white_circle: -0.95%</td> <td nowrap> 315.51µs</td> <td nowrap> 308.77µs</td> <td nowrap> :green_circle: -2.08%</td> <td nowrap> :yellow_circle: 91%</td></tr><tr><td><tt>translate/</tt><br><tt>spidermonkey</td> <td nowrap> 0.00ns</td> <td nowrap> 0.00ns</td> <td nowrap> :white_circle: -0.82%</td> <td nowrap> 0.00ns</td> <td nowrap> 0.00ns</td> <td nowrap> :green_circle: -1.52%</td> <td nowrap> :green_circle: 0%</td></tr><tr><td><tt>translate/</tt><br><tt>wasm_kernel</td> <td nowrap> 4.11ms</td> <td nowrap> 4.12ms</td> <td nowrap> :white_circle: -0.46%</td> <td nowrap> 8.31ms</td> <td nowrap> 8.18ms</td> <td nowrap> :green_circle: -1.59%</td> <td nowrap> :yellow_circle: 99%</td></tr> </tbody> </table> 

 [Link to pipeline](https://gitlab.parity.io/parity/mirrors/wasmi/-/jobs/2440496)

**Comment by Robbepop** [comment]
As of now I don't know where the double digit performance regressions in some native benchmarks are coming from. I can reproduce them locally. Will need some research about this before merging this PR. It is very weird since this PR does not even remotely touch the execution engine of `wasmi`.

**Comment by Robbepop** [comment]
This PR in its current state is not mergeable due to the massive performance regressions on the Wasm target.

**Comment by Robbepop** [comment]
Performance regressions seems to be resolved with the most recent merge with `master` so we can finally merge this PR.

**Comment by flavio** [comment]
Sweet, I'll update my wit-bindgen code to make use of it :)

**Pull request merged**
