### PR TITLE
feat: add into_inner to Pages

### PR DESCRIPTION
**Pull request by yjhmelody**
I need it.

### CODE REVIEW

**Comment by Robbepop** [comment]
> I need it.

Please elaborate what for.

**Comment by paritytech-cicd-pr** [comment]
## BENCHMARKS ## 

 <table> <thead> <tr> <th></th><th colspan=3>NATIVE</th><th colspan=3>WASMTIME</th><th></th> </tr> <tr> <th>BENCHMARK</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>WASMTIME OVERHEAD</th> </tr> </thead> <tbody> <tr><td><tt>execute/</tt><br><tt>bare_call_0</td> <td nowrap> 1.27ms</td> <td nowrap> 1.26ms</td> <td nowrap> :white_circle: -0.15%</td> <td nowrap> 1.11ms</td> <td nowrap> 1.11ms</td> <td nowrap> :white_circle: 0.43%</td> <td nowrap> :green_circle: -12%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_0/typed</td> <td nowrap> 705.32µs</td> <td nowrap> 704.73µs</td> <td nowrap> :white_circle: -0.03%</td> <td nowrap> 538.14µs</td> <td nowrap> 535.19µs</td> <td nowrap> :white_circle: -0.61%</td> <td nowrap> :green_circle: -24%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_1</td> <td nowrap> 1.40ms</td> <td nowrap> 1.41ms</td> <td nowrap> :white_circle: 0.65%</td> <td nowrap> 1.37ms</td> <td nowrap> 1.38ms</td> <td nowrap> :red_circle: 0.76%</td> <td nowrap> :green_circle: -2%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_16</td> <td nowrap> 2.99ms</td> <td nowrap> 2.98ms</td> <td nowrap> :white_circle: -0.13%</td> <td nowrap> 5.07ms</td> <td nowrap> 5.11ms</td> <td nowrap> :red_circle: 0.64%</td> <td nowrap> :yellow_circle: 72%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_16/typed</td> <td nowrap> 1.28ms</td> <td nowrap> 1.28ms</td> <td nowrap> :white_circle: -0.52%</td> <td nowrap> 2.37ms</td> <td nowrap> 2.40ms</td> <td nowrap> :red_circle: 1.18%</td> <td nowrap> :yellow_circle: 88%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_1/typed</td> <td nowrap> 805.85µs</td> <td nowrap> 819.72µs</td> <td nowrap> :white_circle: 1.94%</td> <td nowrap> 865.98µs</td> <td nowrap> 892.42µs</td> <td nowrap> :red_circle: 3.10%</td> <td nowrap> :green_circle: 9%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_4</td> <td nowrap> 1.75ms</td> <td nowrap> 1.75ms</td> <td nowrap> :white_circle: 0.01%</td> <td nowrap> 2.13ms</td> <td nowrap> 2.16ms</td> <td nowrap> :red_circle: 0.95%</td> <td nowrap> :green_circle: 23%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_4/typed</td> <td nowrap> 889.92µs</td> <td nowrap> 891.13µs</td> <td nowrap> :white_circle: 0.13%</td> <td nowrap> 988.79µs</td> <td nowrap> 1.00ms</td> <td nowrap> :red_circle: 1.39%</td> <td nowrap> :green_circle: 13%</td></tr><tr><td><tt>execute/</tt><br><tt>br_table</td> <td nowrap> 919.51µs</td> <td nowrap> 914.67µs</td> <td nowrap> :white_circle: -0.62%</td> <td nowrap> 1.10ms</td> <td nowrap> 1.10ms</td> <td nowrap> :white_circle: 0.29%</td> <td nowrap> :green_circle: 20%</td></tr><tr><td><tt>execute/</tt><br><tt>count_until</td> <td nowrap> 1.20ms</td> <td nowrap> 902.88µs</td> <td nowrap> :green_circle: -24.52%</td> <td nowrap> 2.33ms</td> <td nowrap> 2.34ms</td> <td nowrap> :white_circle: 0.22%</td> <td nowrap> :red_circle: 159%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial_iterative</td> <td nowrap> 364.09µs</td> <td nowrap> 364.27µs</td> <td nowrap> :white_circle: 0.03%</td> <td nowrap> 941.21µs</td> <td nowrap> 930.38µs</td> <td nowrap> :green_circle: -1.24%</td> <td nowrap> :red_circle: 155%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial_recursive</td> <td nowrap> 722.71µs</td> <td nowrap> 720.74µs</td> <td nowrap> :white_circle: -0.25%</td> <td nowrap> 1.55ms</td> <td nowrap> 1.54ms</td> <td nowrap> :white_circle: -0.72%</td> <td nowrap> :red_circle: 114%</td></tr><tr><td><tt>execute/</tt><br><tt>fib_iterative</td> <td nowrap> 1.79ms</td> <td nowrap> 1.79ms</td> <td nowrap> :white_circle: -0.02%</td> <td nowrap> 5.03ms</td> <td nowrap> 5.04ms</td> <td nowrap> :white_circle: 0.12%</td> <td nowrap> :red_circle: 182%</td></tr><tr><td><tt>execute/</tt><br><tt>fib_recursive</td> <td nowrap> 8.18ms</td> <td nowrap> 8.17ms</td> <td nowrap> :white_circle: -0.04%</td> <td nowrap> 14.15ms</td> <td nowrap> 14.23ms</td> <td nowrap> :white_circle: 0.57%</td> <td nowrap> :yellow_circle: 74%</td></tr><tr><td><tt>execute/</tt><br><tt>global_bump</td> <td nowrap> 1.36ms</td> <td nowrap> 1.36ms</td> <td nowrap> :white_circle: -0.05%</td> <td nowrap> 3.85ms</td> <td nowrap> 3.68ms</td> <td nowrap> :green_circle: -4.63%</td> <td nowrap> :red_circle: 170%</td></tr><tr><td><tt>execute/</tt><br><tt>host_calls</td> <td nowrap> 33.63µs</td> <td nowrap> 32.65µs</td> <td nowrap> :white_circle: -1.84%</td> <td nowrap> 44.37µs</td> <td nowrap> 44.36µs</td> <td nowrap> :white_circle: 0.11%</td> <td nowrap> :green_circle: 36%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_fill</td> <td nowrap> 1.55ms</td> <td nowrap> 1.55ms</td> <td nowrap> :white_circle: 0.01%</td> <td nowrap> 4.22ms</td> <td nowrap> 4.24ms</td> <td nowrap> :white_circle: 0.34%</td> <td nowrap> :red_circle: 173%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_sum</td> <td nowrap> 1.55ms</td> <td nowrap> 1.55ms</td> <td nowrap> :white_circle: -0.14%</td> <td nowrap> 4.24ms</td> <td nowrap> 4.25ms</td> <td nowrap> :white_circle: 0.15%</td> <td nowrap> :red_circle: 174%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_vec_add</td> <td nowrap> 3.05ms</td> <td nowrap> 3.05ms</td> <td nowrap> :white_circle: 0.00%</td> <td nowrap> 8.67ms</td> <td nowrap> 8.67ms</td> <td nowrap> :white_circle: 0.08%</td> <td nowrap> :red_circle: 184%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_is_even</td> <td nowrap> 1.30ms</td> <td nowrap> 1.30ms</td> <td nowrap> :white_circle: -0.05%</td> <td nowrap> 2.61ms</td> <td nowrap> 2.63ms</td> <td nowrap> :white_circle: 0.76%</td> <td nowrap> :red_circle: 103%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_ok</td> <td nowrap> 171.14µs</td> <td nowrap> 174.95µs</td> <td nowrap> :red_circle: 2.07%</td> <td nowrap> 362.68µs</td> <td nowrap> 361.30µs</td> <td nowrap> :white_circle: -0.16%</td> <td nowrap> :red_circle: 107%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_scan</td> <td nowrap> 215.29µs</td> <td nowrap> 215.32µs</td> <td nowrap> :white_circle: 0.10%</td> <td nowrap> 465.14µs</td> <td nowrap> 466.62µs</td> <td nowrap> :white_circle: 0.18%</td> <td nowrap> :red_circle: 117%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_trap</td> <td nowrap> 17.04µs</td> <td nowrap> 17.04µs</td> <td nowrap> :white_circle: -0.02%</td> <td nowrap> 36.14µs</td> <td nowrap> 36.78µs</td> <td nowrap> :red_circle: 1.84%</td> <td nowrap> :red_circle: 116%</td></tr><tr><td><tt>execute/</tt><br><tt>regex_redux</td> <td nowrap> 674.82µs</td> <td nowrap> 675.15µs</td> <td nowrap> :white_circle: 0.02%</td> <td nowrap> 1.59ms</td> <td nowrap> 1.59ms</td> <td nowrap> :white_circle: -0.05%</td> <td nowrap> :red_circle: 136%</td></tr><tr><td><tt>execute/</tt><br><tt>rev_complement</td> <td nowrap> 601.89µs</td> <td nowrap> 590.25µs</td> <td nowrap> :white_circle: -1.61%</td> <td nowrap> 1.53ms</td> <td nowrap> 1.55ms</td> <td nowrap> :red_circle: 1.36%</td> <td nowrap> :red_circle: 163%</td></tr><tr><td><tt>execute/</tt><br><tt>tiny_keccak</td> <td nowrap> 476.00µs</td> <td nowrap> 461.08µs</td> <td nowrap> :green_circle: -3.46%</td> <td nowrap> 1.37ms</td> <td nowrap> 1.39ms</td> <td nowrap> :red_circle: 1.54%</td> <td nowrap> :red_circle: 201%</td></tr><tr><td><tt>execute/</tt><br><tt>trunc_f2i</td> <td nowrap> 1.08ms</td> <td nowrap> 1.08ms</td> <td nowrap> :white_circle: -0.16%</td> <td nowrap> 2.65ms</td> <td nowrap> 2.66ms</td> <td nowrap> :white_circle: 0.51%</td> <td nowrap> :red_circle: 147%</td></tr><tr><td><tt>instantiate/</tt><br><tt>wasm_kernel</td> <td nowrap> 72.07µs</td> <td nowrap> 70.43µs</td> <td nowrap> :white_circle: -1.38%</td> <td nowrap> 121.25µs</td> <td nowrap> 121.61µs</td> <td nowrap> :white_circle: -0.03%</td> <td nowrap> :yellow_circle: 73%</td></tr><tr><td><tt>translate/</tt><br><tt>wasm_kernel</td> <td nowrap> 4.16ms</td> <td nowrap> 4.18ms</td> <td nowrap> :white_circle: 0.21%</td> <td nowrap> 7.90ms</td> <td nowrap> 8.09ms</td> <td nowrap> :red_circle: 2.28%</td> <td nowrap> :yellow_circle: 94%</td></tr> </tbody> </table> 

 [Link to pipeline](https://gitlab.parity.io/parity/mirrors/wasmi/-/jobs/1975500)

**Comment by Robbepop** [comment]
No sufficient elaboration for the motivation was given, therefore  I close this PR now.

**Comment by yjhmelody** [comment]
> > I need it.
> 
> Please elaborate what for.

I am implement a snapshot for wasm instance. So I need to record the real data type for it.

**Pull request closed without merging**
