### PR TITLE
CI: Add pull after checking out `master` for Benchmark CI

### PR DESCRIPTION
**Pull request by sergejparity**
It appears that in sometimes `master` branch is out of sync.
Like here https://gitlab.parity.io/parity/mirrors/wasmi/-/jobs/1868177#L29
```
$ git checkout master
Previous HEAD position was 2efb5fe add missing import after merge
Switched to branch 'master'
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
```
This PR fixes that

### CODE REVIEW

**Comment by Robbepop** [comment]
Thanks @sergejparity for the quick fix! Let's wait for the benchmark results.

**Comment by paritytech-cicd-pr** [comment]
## CRITERION BENCHMARKS ## 

 |BENCHMARK|MASTER|PR|Diff|
 |---|---|---|---|
 | `compile_and_validate_v1`  | 5.4609 ms  | 5.4760 ms  | :white_circle:  +0.3462% |
| `execute_count_until_v1`  |  967.46 µs   | 2.0380 ms  | :red_circle:  +108.01% |
| `execute_factorial_iterative_v1`  | 438.40 ns  | 922.28 ns  | :red_circle:  +109.93% |
| `execute_factorial_recursive_v1`  |  1.0909 µs   |  1.2647 µs   | :red_circle:  +15.939% |
| `execute_fib_iterative_v1`  | 2.2761 ms  | 4.8022 ms  | :red_circle:  +110.98% |
| `execute_fib_recursive_v1`  | 9.6275 ms  | 11.341 ms  | :red_circle:  +18.229% |
| `execute_global_bump_v1`  | 1.3937 ms  | 2.8166 ms  | :red_circle:  +102.08% |
| `execute_host_calls_v1`  |  32.325 µs   |  30.728 µs   | :green_circle:  -4.9773% |
| `execute_memory_fill_v1`  | 1.7390 ms  | 4.0537 ms  | :red_circle:  +133.20% |
| `execute_memory_sum_v1`  | 1.7960 ms  | 3.8004 ms  | :red_circle:  +109.73% |
| `execute_memory_vec_add_v1`  | 3.4148 ms  | 8.0550 ms  | :red_circle:  +135.90% |
| `execute_recursive_is_even_v1`  | 1.8652 ms  | 2.2498 ms  | :red_circle:  +20.632% |
| `execute_recursive_ok_v1`  |  286.92 µs   |  301.41 µs   | :red_circle:  +5.5653% |
| `execute_recursive_scan_v1`  |  303.25 µs   |  365.95 µs   | :red_circle:  +21.175% |
| `execute_recursive_trap_v1`  |  26.504 µs   |  25.687 µs   | :green_circle:  -2.9236% |
| `execute_regex_redux_v1`  |  934.72 µs   | 1.3869 ms  | :red_circle:  +48.942% |
| `execute_rev_complement_v1`  |  670.43 µs   | 1.3921 ms  | :red_circle:  +107.68% |
| `execute_tiny_keccak_v1`  |  528.77 µs   | 1.2346 ms  | :red_circle:  +133.27% |
| `execute_trunc_f2i_v1`  | 1.1384 ms  | 1.8024 ms  | :red_circle:  +58.523% |
| `instantiate_v1`  |  73.999 µs   |  72.944 µs   | :white_circle:  -1.2638% |


 [Link to pipeline](https://gitlab.parity.io/parity/mirrors/wasmi/-/jobs/1868367)

**Review by Robbepop — COMMENTED** [review]
Thanks for the fixed.

When you are already at it. Could you please make use of the more efficient (non-bench) GitLab runners? Or is there a technical/practical reason why not to use those for benchmarking even though they are faster? (Still a lot slower than my 2015 laptop ...)

**Comment by Robbepop** [comment]
> > technical/practical reason why not to use those for benchmarking even though they are faster?
> 
> Main reason is to deliver trustworthy results. So we can be sure that difference between tests executed against `master` and `pr` is not the result of random factors like some another jobs started on the runner at the same time.

sounds reasonable, okay :+1:

**Review by Robbepop — APPROVED** [review]

**Pull request merged**
