### PR TITLE
feat(Linker): remove externals from `Linker` and make `instantiate` to use `&self`

### PR DESCRIPTION
**Pull request by yjhmelody**
Just a previous PR, but I mainly want to generalize `instantiate` method

### CODE REVIEW

**Comment by yjhmelody** [comment]
🤔  Maybe I should not alter this method and just add a new one?

**Comment by paritytech-cicd-pr** [comment]
## BENCHMARKS ## 

 <table> <thead> <tr> <th></th><th colspan=3>NATIVE</th><th colspan=3>WASMTIME</th><th></th> </tr> <tr> <th>BENCHMARK</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>WASMTIME OVERHEAD</th> </tr> </thead> <tbody> <tr><td><tt>execute/</tt><br><tt>count_until</td> <td nowrap> 947.12µs</td> <td nowrap> 918.74µs</td> <td nowrap> :green_circle: -3.17%</td> <td nowrap> 2.38ms</td> <td nowrap> 2.38ms</td> <td nowrap> :white_circle: 0.00%</td> <td nowrap> :red_circle: 159%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial_iterative</td> <td nowrap> 401.70ns</td> <td nowrap> 398.65ns</td> <td nowrap> :white_circle: -0.80%</td> <td nowrap> 997.16ns</td> <td nowrap> 998.89ns</td> <td nowrap> :white_circle: 0.26%</td> <td nowrap> :red_circle: 151%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial_recursive</td> <td nowrap> 763.97ns</td> <td nowrap> 783.94ns</td> <td nowrap> :red_circle: 2.67%</td> <td nowrap> 1.55µs</td> <td nowrap> 1.57µs</td> <td nowrap> :white_circle: 0.70%</td> <td nowrap> :yellow_circle: 100%</td></tr><tr><td><tt>execute/</tt><br><tt>fib_iterative</td> <td nowrap> 1.80ms</td> <td nowrap> 1.87ms</td> <td nowrap> :red_circle: 3.74%</td> <td nowrap> 5.11ms</td> <td nowrap> 5.11ms</td> <td nowrap> :white_circle: -0.04%</td> <td nowrap> :red_circle: 174%</td></tr><tr><td><tt>execute/</tt><br><tt>fib_recursive</td> <td nowrap> 7.01ms</td> <td nowrap> 7.16ms</td> <td nowrap> :red_circle: 2.22%</td> <td nowrap> 14.03ms</td> <td nowrap> 14.29ms</td> <td nowrap> :red_circle: 1.93%</td> <td nowrap> :yellow_circle: 99%</td></tr><tr><td><tt>execute/</tt><br><tt>global_bump</td> <td nowrap> 1.48ms</td> <td nowrap> 1.36ms</td> <td nowrap> :green_circle: -7.84%</td> <td nowrap> 3.64ms</td> <td nowrap> 4.63ms</td> <td nowrap> :red_circle: 27.16%</td> <td nowrap> :red_circle: 240%</td></tr><tr><td><tt>execute/</tt><br><tt>host_calls</td> <td nowrap> 32.00µs</td> <td nowrap> 32.32µs</td> <td nowrap> :white_circle: 0.19%</td> <td nowrap> 45.20µs</td> <td nowrap> 45.11µs</td> <td nowrap> :white_circle: -0.21%</td> <td nowrap> :green_circle: 40%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_fill</td> <td nowrap> 1.67ms</td> <td nowrap> 1.70ms</td> <td nowrap> :red_circle: 1.64%</td> <td nowrap> 4.33ms</td> <td nowrap> 4.33ms</td> <td nowrap> :white_circle: -0.18%</td> <td nowrap> :red_circle: 155%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_sum</td> <td nowrap> 1.57ms</td> <td nowrap> 1.59ms</td> <td nowrap> :red_circle: 1.28%</td> <td nowrap> 4.36ms</td> <td nowrap> 4.36ms</td> <td nowrap> :white_circle: -0.03%</td> <td nowrap> :red_circle: 174%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_vec_add</td> <td nowrap> 3.25ms</td> <td nowrap> 3.16ms</td> <td nowrap> :green_circle: -2.72%</td> <td nowrap> 8.94ms</td> <td nowrap> 8.94ms</td> <td nowrap> :white_circle: -0.02%</td> <td nowrap> :red_circle: 183%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_is_even</td> <td nowrap> 1.35ms</td> <td nowrap> 1.35ms</td> <td nowrap> :white_circle: -0.11%</td> <td nowrap> 2.55ms</td> <td nowrap> 2.57ms</td> <td nowrap> :white_circle: 0.68%</td> <td nowrap> :yellow_circle: 90%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_ok</td> <td nowrap> 179.57µs</td> <td nowrap> 181.76µs</td> <td nowrap> :red_circle: 1.29%</td> <td nowrap> 349.32µs</td> <td nowrap> 356.84µs</td> <td nowrap> :red_circle: 2.19%</td> <td nowrap> :yellow_circle: 96%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_scan</td> <td nowrap> 219.62µs</td> <td nowrap> 216.80µs</td> <td nowrap> :white_circle: -1.47%</td> <td nowrap> 485.37µs</td> <td nowrap> 460.62µs</td> <td nowrap> :green_circle: -5.20%</td> <td nowrap> :red_circle: 112%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_trap</td> <td nowrap> 17.73µs</td> <td nowrap> 17.21µs</td> <td nowrap> :green_circle: -2.97%</td> <td nowrap> 36.89µs</td> <td nowrap> 35.75µs</td> <td nowrap> :green_circle: -3.28%</td> <td nowrap> :red_circle: 108%</td></tr><tr><td><tt>execute/</tt><br><tt>regex_redux</td> <td nowrap> 676.86µs</td> <td nowrap> 720.77µs</td> <td nowrap> :red_circle: 6.83%</td> <td nowrap> 1.60ms</td> <td nowrap> 1.62ms</td> <td nowrap> :red_circle: 1.60%</td> <td nowrap> :red_circle: 125%</td></tr><tr><td><tt>execute/</tt><br><tt>rev_complement</td> <td nowrap> 625.28µs</td> <td nowrap> 618.27µs</td> <td nowrap> :green_circle: -1.24%</td> <td nowrap> 1.55ms</td> <td nowrap> 1.56ms</td> <td nowrap> :white_circle: 0.74%</td> <td nowrap> :red_circle: 153%</td></tr><tr><td><tt>execute/</tt><br><tt>tiny_keccak</td> <td nowrap> 485.53µs</td> <td nowrap> 514.71µs</td> <td nowrap> :red_circle: 6.75%</td> <td nowrap> 1.48ms</td> <td nowrap> 1.42ms</td> <td nowrap> :green_circle: -4.28%</td> <td nowrap> :red_circle: 175%</td></tr><tr><td><tt>execute/</tt><br><tt>trunc_f2i</td> <td nowrap> 1.01ms</td> <td nowrap> 1.02ms</td> <td nowrap> :white_circle: 0.69%</td> <td nowrap> 2.74ms</td> <td nowrap> 2.72ms</td> <td nowrap> :white_circle: -0.51%</td> <td nowrap> :red_circle: 166%</td></tr><tr><td><tt>instantiate/</tt><br><tt>wasm_kernel</td> <td nowrap> 67.73µs</td> <td nowrap> 67.77µs</td> <td nowrap> :white_circle: 0.79%</td> <td nowrap> 126.62µs</td> <td nowrap> 94.25µs</td> <td nowrap> :green_circle: -25.43%</td> <td nowrap> :green_circle: 39%</td></tr><tr><td><tt>translate/</tt><br><tt>wasm_kernel</td> <td nowrap> 4.83ms</td> <td nowrap> 4.83ms</td> <td nowrap> :white_circle: -0.12%</td> <td nowrap> 9.58ms</td> <td nowrap> 9.27ms</td> <td nowrap> :green_circle: -3.30%</td> <td nowrap> :yellow_circle: 92%</td></tr> </tbody> </table> 

 [Link to pipeline](https://gitlab.parity.io/parity/mirrors/wasmi/-/jobs/1946936)

**Review by Robbepop — APPROVED** [review]
Hmmm this is already the 2nd time you requested this PR.
However, I took another look and the Wasmtime API also takes a `&self` reference for the `Linker::instantiate` method. So this is indeed bad since we ideally want to mirror the Wasmtime API as closely as possible.
Since your changes do not display significant performance differences I am inclined to actually merging it. However, it is not ideal since we are (again) very dependent on Rust and LLVM optimizing the allocations away. If those optimizations no longer apply we will see significant regressions.

**Comment by yjhmelody** [comment]
@Robbepop you could keep the inner buf, but add a `&mut self` version.

**Comment by Robbepop** [comment]
> @Robbepop you could keep the inner buf, but add a `&mut self` version.

As I said we want to closely mirror the Wasmtime API and since the Wasmtime API does not have 2 APIs for that functionality we won't introduce them either.

**Pull request merged**
