### PR TITLE
feat: make Module::imports be `pub`

### PR DESCRIPTION
**Pull request by yjhmelody**
If we want to create stub function, we must need to know the imports info.

I think substrate also need this method to do `prepare_import` like wasmtime.

### CODE REVIEW

**Review by Robbepop — APPROVED** [review]
LGTM Also Wasmtime has this exact same API.

**Comment by Robbepop** [comment]
This PR is missing re-exporting the type `ModuleImportsIter` as public at the `lib.rs`. Should be a single line addition.

**Comment by paritytech-cicd-pr** [comment]
## BENCHMARKS ## 

 <table> <thead> <tr> <th></th><th colspan=3>NATIVE</th><th colspan=3>WASMTIME</th><th></th> </tr> <tr> <th>BENCHMARK</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>WASMTIME OVERHEAD</th> </tr> </thead> <tbody> <tr><td><tt>execute/</tt><br><tt>bare_call_0</td> <td nowrap> 1.01ms</td> <td nowrap> 1.03ms</td> <td nowrap> :red_circle: 0.25%</td> <td nowrap> 965.66µs</td> <td nowrap> 989.07µs</td> <td nowrap> :red_circle: 2.39%</td> <td nowrap> :green_circle: -4%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_0/typed</td> <td nowrap> 514.95µs</td> <td nowrap> 521.08µs</td> <td nowrap> :red_circle: 1.26%</td> <td nowrap> 452.42µs</td> <td nowrap> 454.77µs</td> <td nowrap> :white_circle: 0.45%</td> <td nowrap> :green_circle: -13%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_1</td> <td nowrap> 1.06ms</td> <td nowrap> 1.05ms</td> <td nowrap> :white_circle: -0.65%</td> <td nowrap> 1.18ms</td> <td nowrap> 1.23ms</td> <td nowrap> :red_circle: 3.71%</td> <td nowrap> :green_circle: 17%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_16</td> <td nowrap> 2.11ms</td> <td nowrap> 2.10ms</td> <td nowrap> :white_circle: -0.48%</td> <td nowrap> 4.73ms</td> <td nowrap> 4.70ms</td> <td nowrap> :red_circle: -0.50%</td> <td nowrap> :red_circle: 124%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_16/typed</td> <td nowrap> 1.52ms</td> <td nowrap> 1.54ms</td> <td nowrap> :white_circle: 0.54%</td> <td nowrap> 2.32ms</td> <td nowrap> 2.42ms</td> <td nowrap> :red_circle: 4.04%</td> <td nowrap> :yellow_circle: 57%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_1/typed</td> <td nowrap> 611.13µs</td> <td nowrap> 605.90µs</td> <td nowrap> :white_circle: -0.84%</td> <td nowrap> 736.44µs</td> <td nowrap> 778.43µs</td> <td nowrap> :red_circle: 5.48%</td> <td nowrap> :green_circle: 28%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_4</td> <td nowrap> 1.20ms</td> <td nowrap> 1.21ms</td> <td nowrap> :white_circle: 0.70%</td> <td nowrap> 1.90ms</td> <td nowrap> 2.02ms</td> <td nowrap> :red_circle: 6.04%</td> <td nowrap> :yellow_circle: 66%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_4/typed</td> <td nowrap> 633.99µs</td> <td nowrap> 628.12µs</td> <td nowrap> :white_circle: -0.67%</td> <td nowrap> 906.13µs</td> <td nowrap> 904.36µs</td> <td nowrap> :white_circle: -0.36%</td> <td nowrap> :green_circle: 44%</td></tr><tr><td><tt>execute/</tt><br><tt>br_table</td> <td nowrap> 626.93µs</td> <td nowrap> 628.34µs</td> <td nowrap> :white_circle: 0.13%</td> <td nowrap> 984.79µs</td> <td nowrap> 985.98µs</td> <td nowrap> :white_circle: 0.39%</td> <td nowrap> :yellow_circle: 57%</td></tr><tr><td><tt>execute/</tt><br><tt>count_until</td> <td nowrap> 711.25µs</td> <td nowrap> 712.14µs</td> <td nowrap> :white_circle: 0.04%</td> <td nowrap> 2.19ms</td> <td nowrap> 2.19ms</td> <td nowrap> :white_circle: -0.23%</td> <td nowrap> :red_circle: 207%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial_iterative</td> <td nowrap> 369.12µs</td> <td nowrap> 306.34µs</td> <td nowrap> :green_circle: -17.17%</td> <td nowrap> 866.37µs</td> <td nowrap> 866.02µs</td> <td nowrap> :white_circle: -0.03%</td> <td nowrap> :red_circle: 183%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial_recursive</td> <td nowrap> 605.47µs</td> <td nowrap> 621.52µs</td> <td nowrap> :red_circle: 2.64%</td> <td nowrap> 1.29ms</td> <td nowrap> 1.29ms</td> <td nowrap> :white_circle: 0.34%</td> <td nowrap> :red_circle: 107%</td></tr><tr><td><tt>execute/</tt><br><tt>fib_iterative</td> <td nowrap> 1.49ms</td> <td nowrap> 1.43ms</td> <td nowrap> :green_circle: -3.88%</td> <td nowrap> 4.62ms</td> <td nowrap> 4.62ms</td> <td nowrap> :white_circle: -0.03%</td> <td nowrap> :red_circle: 223%</td></tr><tr><td><tt>execute/</tt><br><tt>fib_recursive</td> <td nowrap> 5.75ms</td> <td nowrap> 5.94ms</td> <td nowrap> :red_circle: 3.35%</td> <td nowrap> 11.83ms</td> <td nowrap> 11.78ms</td> <td nowrap> :white_circle: -0.47%</td> <td nowrap> :yellow_circle: 98%</td></tr><tr><td><tt>execute/</tt><br><tt>global_bump</td> <td nowrap> 1.01ms</td> <td nowrap> 1.01ms</td> <td nowrap> :white_circle: -0.24%</td> <td nowrap> 3.15ms</td> <td nowrap> 3.13ms</td> <td nowrap> :white_circle: -0.39%</td> <td nowrap> :red_circle: 211%</td></tr><tr><td><tt>execute/</tt><br><tt>global_const</td> <td nowrap> 804.73µs</td> <td nowrap> 718.72µs</td> <td nowrap> :green_circle: -10.61%</td> <td nowrap> 2.59ms</td> <td nowrap> 2.60ms</td> <td nowrap> :white_circle: 0.72%</td> <td nowrap> :red_circle: 262%</td></tr><tr><td><tt>execute/</tt><br><tt>host_calls</td> <td nowrap> 28.98µs</td> <td nowrap> 28.77µs</td> <td nowrap> :white_circle: -0.79%</td> <td nowrap> 41.69µs</td> <td nowrap> 41.69µs</td> <td nowrap> :white_circle: 0.03%</td> <td nowrap> :green_circle: 45%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_fill</td> <td nowrap> 1.35ms</td> <td nowrap> 1.31ms</td> <td nowrap> :green_circle: -2.94%</td> <td nowrap> 4.20ms</td> <td nowrap> 4.21ms</td> <td nowrap> :white_circle: 0.26%</td> <td nowrap> :red_circle: 222%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_sum</td> <td nowrap> 1.34ms</td> <td nowrap> 1.30ms</td> <td nowrap> :green_circle: -3.17%</td> <td nowrap> 4.25ms</td> <td nowrap> 4.24ms</td> <td nowrap> :white_circle: -0.17%</td> <td nowrap> :red_circle: 225%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_vec_add</td> <td nowrap> 2.68ms</td> <td nowrap> 2.59ms</td> <td nowrap> :green_circle: -3.29%</td> <td nowrap> 8.48ms</td> <td nowrap> 8.48ms</td> <td nowrap> :white_circle: 0.10%</td> <td nowrap> :red_circle: 227%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_is_even</td> <td nowrap> 1.11ms</td> <td nowrap> 1.11ms</td> <td nowrap> :white_circle: -0.77%</td> <td nowrap> 2.10ms</td> <td nowrap> 2.12ms</td> <td nowrap> :white_circle: 0.39%</td> <td nowrap> :yellow_circle: 91%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_ok</td> <td nowrap> 143.30µs</td> <td nowrap> 142.49µs</td> <td nowrap> :white_circle: -0.49%</td> <td nowrap> 306.27µs</td> <td nowrap> 316.10µs</td> <td nowrap> :red_circle: 3.23%</td> <td nowrap> :red_circle: 122%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_scan</td> <td nowrap> 179.12µs</td> <td nowrap> 178.00µs</td> <td nowrap> :white_circle: -0.53%</td> <td nowrap> 387.07µs</td> <td nowrap> 390.31µs</td> <td nowrap> :white_circle: 0.82%</td> <td nowrap> :red_circle: 119%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_trap</td> <td nowrap> 14.00µs</td> <td nowrap> 14.08µs</td> <td nowrap> :white_circle: 0.37%</td> <td nowrap> 30.09µs</td> <td nowrap> 32.06µs</td> <td nowrap> :red_circle: 6.82%</td> <td nowrap> :red_circle: 128%</td></tr><tr><td><tt>execute/</tt><br><tt>regex_redux</td> <td nowrap> 544.54µs</td> <td nowrap> 542.23µs</td> <td nowrap> :white_circle: -0.38%</td> <td nowrap> 1.49ms</td> <td nowrap> 1.50ms</td> <td nowrap> :white_circle: 0.30%</td> <td nowrap> :red_circle: 177%</td></tr><tr><td><tt>execute/</tt><br><tt>rev_complement</td> <td nowrap> 500.89µs</td> <td nowrap> 506.08µs</td> <td nowrap> :white_circle: 1.12%</td> <td nowrap> 1.53ms</td> <td nowrap> 1.50ms</td> <td nowrap> :green_circle: -2.00%</td> <td nowrap> :red_circle: 196%</td></tr><tr><td><tt>execute/</tt><br><tt>tiny_keccak</td> <td nowrap> 368.63µs</td> <td nowrap> 372.81µs</td> <td nowrap> :white_circle: 1.33%</td> <td nowrap> 1.41ms</td> <td nowrap> 1.20ms</td> <td nowrap> :green_circle: -14.81%</td> <td nowrap> :red_circle: 221%</td></tr><tr><td><tt>execute/</tt><br><tt>trunc_f2i</td> <td nowrap> 918.09µs</td> <td nowrap> 912.69µs</td> <td nowrap> :white_circle: -0.54%</td> <td nowrap> 2.52ms</td> <td nowrap> 2.52ms</td> <td nowrap> :white_circle: 0.14%</td> <td nowrap> :red_circle: 176%</td></tr><tr><td><tt>instantiate/</tt><br><tt>wasm_kernel</td> <td nowrap> 59.02µs</td> <td nowrap> 60.35µs</td> <td nowrap> :white_circle: -0.19%</td> <td nowrap> 74.84µs</td> <td nowrap> 95.56µs</td> <td nowrap> :red_circle: 26.76%</td> <td nowrap> :yellow_circle: 58%</td></tr><tr><td><tt>translate/</tt><br><tt>erc1155</td> <td nowrap> 207.09µs</td> <td nowrap> 206.68µs</td> <td nowrap> :white_circle: 0.09%</td> <td nowrap> 406.52µs</td> <td nowrap> 408.24µs</td> <td nowrap> :white_circle: 0.42%</td> <td nowrap> :yellow_circle: 98%</td></tr><tr><td><tt>translate/</tt><br><tt>erc20</td> <td nowrap> 101.96µs</td> <td nowrap> 101.54µs</td> <td nowrap> :white_circle: -0.39%</td> <td nowrap> 199.17µs</td> <td nowrap> 200.56µs</td> <td nowrap> :white_circle: 0.70%</td> <td nowrap> :yellow_circle: 98%</td></tr><tr><td><tt>translate/</tt><br><tt>erc721</td> <td nowrap> 145.83µs</td> <td nowrap> 146.49µs</td> <td nowrap> :white_circle: 0.62%</td> <td nowrap> 289.89µs</td> <td nowrap> 288.22µs</td> <td nowrap> :white_circle: -0.30%</td> <td nowrap> :yellow_circle: 97%</td></tr><tr><td><tt>translate/</tt><br><tt>spidermonkey</td> <td nowrap> 0.00ns</td> <td nowrap> 0.00ns</td> <td nowrap> :white_circle: -0.76%</td> <td nowrap> 0.00ns</td> <td nowrap> 0.00ns</td> <td nowrap> :white_circle: -0.92%</td> <td nowrap> :green_circle: 0%</td></tr><tr><td><tt>translate/</tt><br><tt>wasm_kernel</td> <td nowrap> 3.79ms</td> <td nowrap> 3.74ms</td> <td nowrap> :green_circle: -1.76%</td> <td nowrap> 7.62ms</td> <td nowrap> 7.60ms</td> <td nowrap> :white_circle: -0.42%</td> <td nowrap> :red_circle: 103%</td></tr> </tbody> </table> 

 [Link to pipeline](https://gitlab.parity.io/parity/mirrors/wasmi/-/jobs/2080642)

**Comment by yjhmelody** [comment]
@Robbepop Hi, I will export it later.
But I have another point to mention, which is the same as the purpose of this PR. At present, Func::wrap does not support any number of parameters, which is different from wasmtime, which will make it more troublesome to support `allow_miss_host_function`.

**Comment by Robbepop** [comment]
I will create a PR to fix the `clippy` warnings, then you need to merge it so that we can finally merge your PR.

**Review by Robbepop — CHANGES_REQUESTED** [review]
Changes I'd like to see before we merge:

Since `ModuleImport` is going to be `pub` now we should clean up its API, too.
We should make its `new` constructor as well as its `name` method `pub(crate)`. This way we can also remove `ModuleImportName` from the public re-exports and shrink the `wasmi` API surface again. The `field` and `module` method getters should be sufficient.

**Comment by yjhmelody** [comment]
> 

Ok. I'm updating it.

**Comment by Robbepop** [comment]
> @Robbepop Hi, I will export it later. But I have another point to mention, which is the same as the purpose of this PR. At present, Func::wrap does not support params in vec style now, which is different from wasmtime, will make it more troublesome to support feature such like`allow_miss_host_function`.

I don't understand what you mean by this? What are "params in vec style" for `Func::wrap`? What is the `allow_miss_host_function` feature about exactly? Please elaborate!

This might be better done in a separate PR if at all.

**Comment by yjhmelody** [comment]
> > @Robbepop Hi, I will export it later. But I have another point to mention, which is the same as the purpose of this PR. At present, Func::wrap does not support params in vec style now, which is different from wasmtime, will make it more troublesome to support feature such like`allow_miss_host_function`.
> 
> I don't understand what you mean by this? What are "params in vec style" for `Func::wrap`? What is the `allow_miss_host_function` feature about exactly? Please elaborate!
> 
> This might be better done in a separate PR if at all.

Ok. 
Sorrym I thought that you would have to deal with related upgrades of the substrate in the future, and the implementation may be similar to wasmtime.
https://github.com/paritytech/substrate/blob/8016da9ddf1c10a5a74cc5a273905cfeb60ed82c/client/executor/wasmtime/src/imports.rs#L69-L68

Yes, I'll try it first and then make a new PR

**Comment by yjhmelody** [comment]
@Robbepop  I do know how to fix it:
```
342 |     /// An imported [`Global`].
    |                       ^^^^^^ this item is private
    |
    = note: `-D rustdoc::private-intra-doc-links` implied by `-D warnings`
```

**Review by Robbepop — APPROVED** [review]

**Pull request merged**
