### PR TITLE
Fix the read implementation on no-std

### PR DESCRIPTION
**Pull request by AldaronLau**
Currently behavior is panicking.

### CODE REVIEW

**Review by Robbepop — APPROVED** [review]
LGTM

Thanks a lot for the bug fix. How have you found this bu if I may ask?

**Comment by AldaronLau** [comment]
@Robbepop I found the bug by trying to convert the example in lib.rs to work on no-std, as I was upgrading one of my projects from an older version of wasmi.  First, I had to get rid of the `&mut` from the call to `Module::new()` - then it compiled.  After that, I tried loading my WASM file, and I got an unexpected panic.

**Comment by Robbepop** [comment]
@AldaronLau btw the new `wasmi` engine is still pretty new and therefore not yet battle hardened. We are currently in the process to change that. As of right now I would not recommend using the newest `wasmi` in production.

**Comment by AldaronLau** [comment]
@Robbepop thanks for the warning.  I don't think my project counts a "production" (it's very experimental), so I'll keep testing it.

**Comment by Robbepop** [comment]
@AldaronLau Do you have a link to the experimental project for me?

**Comment by AldaronLau** [comment]
The project is https://github.com/ardaku/quantii, which pulls in https://github.com/ardaku/ardaku, which I was updating to the new version of wasmi.

**Pull request merged**
