### PR TITLE
refactor: make `field` import name non-`Option`

### PR DESCRIPTION
**Pull request by yjhmelody**
I found this `TODO`, so I think could remove `Option` from field name now.

But actually, i do not know if name should be optional in wasm spec.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
## BENCHMARKS ## 

 <table> <thead> <tr> <th></th><th colspan=3>NATIVE</th><th colspan=3>WASMTIME</th><th></th> </tr> <tr> <th>BENCHMARK</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>WASMTIME OVERHEAD</th> </tr> </thead> <tbody> <tr><td><tt>execute/</tt><br><tt>bare_call_0</td> <td nowrap> 1.07ms</td> <td nowrap> 1.01ms</td> <td nowrap> :green_circle: -6.70%</td> <td nowrap> 943.24µs</td> <td nowrap> 996.48µs</td> <td nowrap> :red_circle: 5.72%</td> <td nowrap> :green_circle: -1%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_0/typed</td> <td nowrap> 526.16µs</td> <td nowrap> 520.89µs</td> <td nowrap> :white_circle: -0.97%</td> <td nowrap> 448.03µs</td> <td nowrap> 448.06µs</td> <td nowrap> :white_circle: 0.04%</td> <td nowrap> :green_circle: -14%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_1</td> <td nowrap> 1.13ms</td> <td nowrap> 1.05ms</td> <td nowrap> :red_circle: -6.34%</td> <td nowrap> 1.19ms</td> <td nowrap> 1.17ms</td> <td nowrap> :green_circle: -1.59%</td> <td nowrap> :green_circle: 11%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_16</td> <td nowrap> 2.10ms</td> <td nowrap> 2.19ms</td> <td nowrap> :red_circle: 4.40%</td> <td nowrap> 4.79ms</td> <td nowrap> 4.75ms</td> <td nowrap> :white_circle: 0.13%</td> <td nowrap> :red_circle: 117%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_16/typed</td> <td nowrap> 1.85ms</td> <td nowrap> 1.33ms</td> <td nowrap> :green_circle: -28.30%</td> <td nowrap> 2.28ms</td> <td nowrap> 2.28ms</td> <td nowrap> :white_circle: 0.10%</td> <td nowrap> :yellow_circle: 72%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_1/typed</td> <td nowrap> 633.59µs</td> <td nowrap> 604.82µs</td> <td nowrap> :green_circle: -4.59%</td> <td nowrap> 769.49µs</td> <td nowrap> 761.65µs</td> <td nowrap> :white_circle: -0.87%</td> <td nowrap> :green_circle: 26%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_4</td> <td nowrap> 1.19ms</td> <td nowrap> 1.22ms</td> <td nowrap> :red_circle: 1.75%</td> <td nowrap> 1.92ms</td> <td nowrap> 1.91ms</td> <td nowrap> :green_circle: -0.43%</td> <td nowrap> :yellow_circle: 57%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_4/typed</td> <td nowrap> 624.75µs</td> <td nowrap> 644.54µs</td> <td nowrap> :red_circle: 3.07%</td> <td nowrap> 917.11µs</td> <td nowrap> 893.40µs</td> <td nowrap> :green_circle: -2.94%</td> <td nowrap> :green_circle: 39%</td></tr><tr><td><tt>execute/</tt><br><tt>br_table</td> <td nowrap> 632.37µs</td> <td nowrap> 629.67µs</td> <td nowrap> :white_circle: -0.66%</td> <td nowrap> 995.62µs</td> <td nowrap> 958.96µs</td> <td nowrap> :green_circle: -3.69%</td> <td nowrap> :yellow_circle: 52%</td></tr><tr><td><tt>execute/</tt><br><tt>count_until</td> <td nowrap> 711.87µs</td> <td nowrap> 690.34µs</td> <td nowrap> :green_circle: -3.02%</td> <td nowrap> 2.19ms</td> <td nowrap> 2.19ms</td> <td nowrap> :white_circle: -0.11%</td> <td nowrap> :red_circle: 217%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial_iterative</td> <td nowrap> 306.41µs</td> <td nowrap> 309.57µs</td> <td nowrap> :red_circle: 1.19%</td> <td nowrap> 865.74µs</td> <td nowrap> 867.53µs</td> <td nowrap> :white_circle: 0.31%</td> <td nowrap> :red_circle: 180%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial_recursive</td> <td nowrap> 609.71µs</td> <td nowrap> 603.55µs</td> <td nowrap> :white_circle: -0.86%</td> <td nowrap> 1.28ms</td> <td nowrap> 1.32ms</td> <td nowrap> :red_circle: 2.55%</td> <td nowrap> :red_circle: 118%</td></tr><tr><td><tt>execute/</tt><br><tt>fib_iterative</td> <td nowrap> 1.43ms</td> <td nowrap> 1.55ms</td> <td nowrap> :red_circle: 7.87%</td> <td nowrap> 4.62ms</td> <td nowrap> 4.62ms</td> <td nowrap> :white_circle: 0.01%</td> <td nowrap> :red_circle: 199%</td></tr><tr><td><tt>execute/</tt><br><tt>fib_recursive</td> <td nowrap> 5.74ms</td> <td nowrap> 5.82ms</td> <td nowrap> :red_circle: 1.42%</td> <td nowrap> 11.86ms</td> <td nowrap> 12.18ms</td> <td nowrap> :red_circle: 2.73%</td> <td nowrap> :red_circle: 109%</td></tr><tr><td><tt>execute/</tt><br><tt>global_bump</td> <td nowrap> 1.01ms</td> <td nowrap> 952.15µs</td> <td nowrap> :green_circle: -5.49%</td> <td nowrap> 3.16ms</td> <td nowrap> 3.13ms</td> <td nowrap> :white_circle: -0.99%</td> <td nowrap> :red_circle: 228%</td></tr><tr><td><tt>execute/</tt><br><tt>global_const</td> <td nowrap> 717.02µs</td> <td nowrap> 799.94µs</td> <td nowrap> :red_circle: 11.55%</td> <td nowrap> 2.61ms</td> <td nowrap> 2.51ms</td> <td nowrap> :green_circle: -2.90%</td> <td nowrap> :red_circle: 214%</td></tr><tr><td><tt>execute/</tt><br><tt>host_calls</td> <td nowrap> 28.64µs</td> <td nowrap> 30.42µs</td> <td nowrap> :red_circle: 6.25%</td> <td nowrap> 42.50µs</td> <td nowrap> 41.59µs</td> <td nowrap> :white_circle: -2.42%</td> <td nowrap> :green_circle: 37%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_fill</td> <td nowrap> 1.31ms</td> <td nowrap> 1.30ms</td> <td nowrap> :white_circle: -0.41%</td> <td nowrap> 4.20ms</td> <td nowrap> 4.20ms</td> <td nowrap> :white_circle: -0.36%</td> <td nowrap> :red_circle: 222%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_sum</td> <td nowrap> 1.30ms</td> <td nowrap> 1.33ms</td> <td nowrap> :red_circle: 2.14%</td> <td nowrap> 4.22ms</td> <td nowrap> 4.23ms</td> <td nowrap> :white_circle: 0.46%</td> <td nowrap> :red_circle: 218%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_vec_add</td> <td nowrap> 2.60ms</td> <td nowrap> 2.74ms</td> <td nowrap> :red_circle: 5.36%</td> <td nowrap> 8.47ms</td> <td nowrap> 8.51ms</td> <td nowrap> :white_circle: 0.51%</td> <td nowrap> :red_circle: 211%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_is_even</td> <td nowrap> 1.10ms</td> <td nowrap> 1.16ms</td> <td nowrap> :red_circle: 5.56%</td> <td nowrap> 2.10ms</td> <td nowrap> 2.10ms</td> <td nowrap> :white_circle: 0.35%</td> <td nowrap> :yellow_circle: 81%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_ok</td> <td nowrap> 142.60µs</td> <td nowrap> 150.12µs</td> <td nowrap> :red_circle: 5.16%</td> <td nowrap> 302.01µs</td> <td nowrap> 296.93µs</td> <td nowrap> :white_circle: -1.49%</td> <td nowrap> :yellow_circle: 98%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_scan</td> <td nowrap> 179.99µs</td> <td nowrap> 185.06µs</td> <td nowrap> :red_circle: 2.70%</td> <td nowrap> 384.83µs</td> <td nowrap> 379.58µs</td> <td nowrap> :green_circle: -1.33%</td> <td nowrap> :red_circle: 105%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_trap</td> <td nowrap> 14.14µs</td> <td nowrap> 14.25µs</td> <td nowrap> :white_circle: 0.83%</td> <td nowrap> 30.47µs</td> <td nowrap> 31.78µs</td> <td nowrap> :red_circle: 4.63%</td> <td nowrap> :red_circle: 123%</td></tr><tr><td><tt>execute/</tt><br><tt>regex_redux</td> <td nowrap> 549.58µs</td> <td nowrap> 567.02µs</td> <td nowrap> :red_circle: 3.15%</td> <td nowrap> 1.51ms</td> <td nowrap> 1.53ms</td> <td nowrap> :white_circle: 0.70%</td> <td nowrap> :red_circle: 169%</td></tr><tr><td><tt>execute/</tt><br><tt>rev_complement</td> <td nowrap> 512.94µs</td> <td nowrap> 517.54µs</td> <td nowrap> :white_circle: 0.71%</td> <td nowrap> 1.49ms</td> <td nowrap> 1.51ms</td> <td nowrap> :red_circle: 1.14%</td> <td nowrap> :red_circle: 192%</td></tr><tr><td><tt>execute/</tt><br><tt>tiny_keccak</td> <td nowrap> 375.90µs</td> <td nowrap> 373.40µs</td> <td nowrap> :white_circle: -0.70%</td> <td nowrap> 1.21ms</td> <td nowrap> 1.21ms</td> <td nowrap> :white_circle: 0.00%</td> <td nowrap> :red_circle: 224%</td></tr><tr><td><tt>execute/</tt><br><tt>trunc_f2i</td> <td nowrap> 918.54µs</td> <td nowrap> 916.41µs</td> <td nowrap> :white_circle: -0.26%</td> <td nowrap> 2.52ms</td> <td nowrap> 2.51ms</td> <td nowrap> :white_circle: -0.36%</td> <td nowrap> :red_circle: 174%</td></tr><tr><td><tt>instantiate/</tt><br><tt>wasm_kernel</td> <td nowrap> 61.28µs</td> <td nowrap> 58.16µs</td> <td nowrap> :green_circle: -5.36%</td> <td nowrap> 74.73µs</td> <td nowrap> 74.79µs</td> <td nowrap> :white_circle: -0.81%</td> <td nowrap> :green_circle: 29%</td></tr><tr><td><tt>translate/</tt><br><tt>erc1155</td> <td nowrap> 205.82µs</td> <td nowrap> 207.74µs</td> <td nowrap> :white_circle: 0.63%</td> <td nowrap> 404.27µs</td> <td nowrap> 411.83µs</td> <td nowrap> :red_circle: 1.73%</td> <td nowrap> :yellow_circle: 98%</td></tr><tr><td><tt>translate/</tt><br><tt>erc20</td> <td nowrap> 101.20µs</td> <td nowrap> 101.78µs</td> <td nowrap> :white_circle: 0.54%</td> <td nowrap> 198.25µs</td> <td nowrap> 201.94µs</td> <td nowrap> :red_circle: 1.82%</td> <td nowrap> :yellow_circle: 98%</td></tr><tr><td><tt>translate/</tt><br><tt>erc721</td> <td nowrap> 145.78µs</td> <td nowrap> 147.36µs</td> <td nowrap> :white_circle: 2.11%</td> <td nowrap> 287.03µs</td> <td nowrap> 291.35µs</td> <td nowrap> :white_circle: 1.28%</td> <td nowrap> :yellow_circle: 98%</td></tr><tr><td><tt>translate/</tt><br><tt>spidermonkey</td> <td nowrap> 0.00ns</td> <td nowrap> 0.00ns</td> <td nowrap> :white_circle: 0.77%</td> <td nowrap> 0.00ns</td> <td nowrap> 0.00ns</td> <td nowrap> :red_circle: 2.34%</td> <td nowrap> :green_circle: 0%</td></tr><tr><td><tt>translate/</tt><br><tt>wasm_kernel</td> <td nowrap> 3.76ms</td> <td nowrap> 3.84ms</td> <td nowrap> :white_circle: 1.88%</td> <td nowrap> 7.60ms</td> <td nowrap> 7.79ms</td> <td nowrap> :red_circle: 2.25%</td> <td nowrap> :red_circle: 103%</td></tr> </tbody> </table> 

 [Link to pipeline](https://gitlab.parity.io/parity/mirrors/wasmi/-/jobs/2081073)

**Comment by Robbepop** [comment]
And again: This is not a feature but a refactor.

**Comment by yjhmelody** [comment]
Really? I think the PR break the public APIs. `refactor` means internal APIs break IMO.

**Comment by Robbepop** [comment]
Maybe you are right but I find it hard to imagine this to be a "feature". But generally we do not really use semantic commit messages. This confusion is one of the reasons why I personally do not use them. Also we currently do not auto generate our changelogs which is one of their primary use cases.

**Pull request merged**
