### PR TITLE
Allow mutable exported global. Fix #137

### LINKED ISSUE #137: Implement mutable globals import/export proposal
Should be a pretty simple task: at a glance it looks like we just need to remove checks that prevent importing/exporting of mutable globals.

see:

1. https://github.com/WebAssembly/spec/pull/814
2. https://github.com/WebAssembly/mutable-global

### PR DESCRIPTION
**Pull request by kateinoigakukun**
Ref: https://github.com/WebAssembly/spec/pull/814

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
[clabot:check]

**Comment by NikVolf** [comment]
worth mentioning that it closes #137

**Comment by taegyunkim** [comment]
Hi @kateinoigakukun, are you sill pursuing this? I'm interested in updating testsuites submodule to HEAD, and can help or take from here on. 

For green CI, you have to also update a test in validation subcrate, specifically this one https://github.com/paritytech/wasmi/pull/228/commits/c9f059727e2c3d73d8d6155e47dae45e31dcaae2

**Comment by taegyunkim** [comment]
@kateinoigakukun I'll accept your thumbs up as a sign for me to take this.

**Comment by pepyakin** [comment]
This PR was superseded by #228. Thanks for the effort anyway @kateinoigakukun !

**Pull request closed without merging**
