### PR TITLE
fixes #735: copy paste typo

### LINKED ISSUE #735: len_globals() returns memories.len()
I believe the code for `len_globals` is wrong here -- a copy-paste error from `len_memories` above:

https://github.com/paritytech/wasmi/blob/799995da7afb0ae02bb4fd1c9f242fe07c7ad824/crates/wasmi/src/module/mod.rs#L187-L189

### PR DESCRIPTION
**Pull request by behkod**

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
## BENCHMARKS ## 

 <table> <thead> <tr> <th></th><th colspan=3>NATIVE</th><th colspan=3>WASMTIME</th><th></th> </tr> <tr> <th>BENCHMARK</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>WASMTIME OVERHEAD</th> </tr> </thead> <tbody> <tr><td><tt>execute/</tt><br><tt>bare_call_0</td> <td nowrap> 1.57ms</td> <td nowrap> 1.54ms</td> <td nowrap> :white_circle: -1.86%</td> <td nowrap> 1.05ms</td> <td nowrap> 1.07ms</td> <td nowrap> :red_circle: 2.28%</td> <td nowrap> :green_circle: -30%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_0/typed</td> <td nowrap> 1.15ms</td> <td nowrap> 1.12ms</td> <td nowrap> :white_circle: -2.09%</td> <td nowrap> 674.10µs</td> <td nowrap> 724.38µs</td> <td nowrap> :red_circle: 7.54%</td> <td nowrap> :green_circle: -35%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_1</td> <td nowrap> 1.63ms</td> <td nowrap> 1.60ms</td> <td nowrap> :white_circle: -1.53%</td> <td nowrap> 1.21ms</td> <td nowrap> 1.32ms</td> <td nowrap> :red_circle: 9.25%</td> <td nowrap> :green_circle: -18%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_16</td> <td nowrap> 2.58ms</td> <td nowrap> 2.56ms</td> <td nowrap> :white_circle: -0.93%</td> <td nowrap> 3.55ms</td> <td nowrap> 3.50ms</td> <td nowrap> :green_circle: -1.16%</td> <td nowrap> :green_circle: 37%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_16/typed</td> <td nowrap> 1.57ms</td> <td nowrap> 1.55ms</td> <td nowrap> :white_circle: -1.31%</td> <td nowrap> 1.81ms</td> <td nowrap> 1.81ms</td> <td nowrap> :white_circle: 0.68%</td> <td nowrap> :green_circle: 17%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_1/typed</td> <td nowrap> 1.27ms</td> <td nowrap> 1.25ms</td> <td nowrap> :white_circle: -1.26%</td> <td nowrap> 1.04ms</td> <td nowrap> 1.05ms</td> <td nowrap> :white_circle: 0.94%</td> <td nowrap> :green_circle: -16%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_4</td> <td nowrap> 1.78ms</td> <td nowrap> 1.79ms</td> <td nowrap> :white_circle: -0.16%</td> <td nowrap> 1.64ms</td> <td nowrap> 1.76ms</td> <td nowrap> :red_circle: 7.03%</td> <td nowrap> :green_circle: -2%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_4/typed</td> <td nowrap> 1.26ms</td> <td nowrap> 1.23ms</td> <td nowrap> :white_circle: -2.33%</td> <td nowrap> 941.37µs</td> <td nowrap> 981.60µs</td> <td nowrap> :red_circle: 4.34%</td> <td nowrap> :green_circle: -20%</td></tr><tr><td><tt>execute/</tt><br><tt>br_table</td> <td nowrap> 1.38ms</td> <td nowrap> 1.34ms</td> <td nowrap> :green_circle: -2.60%</td> <td nowrap> 1.18ms</td> <td nowrap> 1.23ms</td> <td nowrap> :red_circle: 4.17%</td> <td nowrap> :green_circle: -8%</td></tr><tr><td><tt>execute/</tt><br><tt>count_until</td> <td nowrap> 621.21µs</td> <td nowrap> 576.60µs</td> <td nowrap> :green_circle: -7.24%</td> <td nowrap> 1.30ms</td> <td nowrap> 1.35ms</td> <td nowrap> :red_circle: 3.77%</td> <td nowrap> :red_circle: 134%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial_iterative</td> <td nowrap> 326.22µs</td> <td nowrap> 319.84µs</td> <td nowrap> :green_circle: -1.99%</td> <td nowrap> 668.48µs</td> <td nowrap> 679.80µs</td> <td nowrap> :red_circle: 1.62%</td> <td nowrap> :red_circle: 113%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial_recursive</td> <td nowrap> 611.64µs</td> <td nowrap> 513.81µs</td> <td nowrap> :green_circle: -15.95%</td> <td nowrap> 870.09µs</td> <td nowrap> 912.63µs</td> <td nowrap> :red_circle: 4.81%</td> <td nowrap> :yellow_circle: 78%</td></tr><tr><td><tt>execute/</tt><br><tt>fibonacci_iter</td> <td nowrap> 1.40ms</td> <td nowrap> 1.39ms</td> <td nowrap> :white_circle: -0.11%</td> <td nowrap> 3.23ms</td> <td nowrap> 3.23ms</td> <td nowrap> :white_circle: -0.14%</td> <td nowrap> :red_circle: 132%</td></tr><tr><td><tt>execute/</tt><br><tt>fibonacci_rec</td> <td nowrap> 4.38ms</td> <td nowrap> 4.34ms</td> <td nowrap> :white_circle: -0.93%</td> <td nowrap> 7.58ms</td> <td nowrap> 7.82ms</td> <td nowrap> :red_circle: 3.23%</td> <td nowrap> :yellow_circle: 80%</td></tr><tr><td><tt>execute/</tt><br><tt>fibonacci_tail</td> <td nowrap> 974.18µs</td> <td nowrap> 978.06µs</td> <td nowrap> :white_circle: 0.48%</td> <td nowrap> 1.88ms</td> <td nowrap> 1.90ms</td> <td nowrap> :white_circle: 1.00%</td> <td nowrap> :yellow_circle: 94%</td></tr><tr><td><tt>execute/</tt><br><tt>global_bump</td> <td nowrap> 741.47µs</td> <td nowrap> 740.22µs</td> <td nowrap> :white_circle: -0.17%</td> <td nowrap> 1.66ms</td> <td nowrap> 1.72ms</td> <td nowrap> :red_circle: 3.63%</td> <td nowrap> :red_circle: 133%</td></tr><tr><td><tt>execute/</tt><br><tt>global_const</td> <td nowrap> 661.09µs</td> <td nowrap> 682.37µs</td> <td nowrap> :red_circle: 2.89%</td> <td nowrap> 1.68ms</td> <td nowrap> 1.67ms</td> <td nowrap> :white_circle: -0.50%</td> <td nowrap> :red_circle: 145%</td></tr><tr><td><tt>execute/</tt><br><tt>host_calls</td> <td nowrap> 36.40µs</td> <td nowrap> 37.04µs</td> <td nowrap> :red_circle: 1.49%</td> <td nowrap> 39.57µs</td> <td nowrap> 45.09µs</td> <td nowrap> :red_circle: 14.05%</td> <td nowrap> :green_circle: 22%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_fill</td> <td nowrap> 1.15ms</td> <td nowrap> 1.17ms</td> <td nowrap> :red_circle: 1.23%</td> <td nowrap> 2.62ms</td> <td nowrap> 2.62ms</td> <td nowrap> :white_circle: -0.12%</td> <td nowrap> :red_circle: 124%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_sum</td> <td nowrap> 1.18ms</td> <td nowrap> 1.14ms</td> <td nowrap> :green_circle: -3.26%</td> <td nowrap> 2.42ms</td> <td nowrap> 2.49ms</td> <td nowrap> :red_circle: 2.62%</td> <td nowrap> :red_circle: 118%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_vec_add</td> <td nowrap> 2.50ms</td> <td nowrap> 2.31ms</td> <td nowrap> :green_circle: -7.53%</td> <td nowrap> 5.23ms</td> <td nowrap> 5.24ms</td> <td nowrap> :white_circle: 0.51%</td> <td nowrap> :red_circle: 127%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_is_even</td> <td nowrap> 710.33µs</td> <td nowrap> 712.13µs</td> <td nowrap> :white_circle: 0.19%</td> <td nowrap> 1.28ms</td> <td nowrap> 1.29ms</td> <td nowrap> :white_circle: 1.56%</td> <td nowrap> :yellow_circle: 81%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_ok</td> <td nowrap> 103.23µs</td> <td nowrap> 102.92µs</td> <td nowrap> :white_circle: -0.45%</td> <td nowrap> 190.64µs</td> <td nowrap> 190.35µs</td> <td nowrap> :white_circle: -0.39%</td> <td nowrap> :yellow_circle: 85%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_scan</td> <td nowrap> 139.80µs</td> <td nowrap> 139.56µs</td> <td nowrap> :white_circle: -0.25%</td> <td nowrap> 247.00µs</td> <td nowrap> 241.67µs</td> <td nowrap> :green_circle: -2.20%</td> <td nowrap> :yellow_circle: 73%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_trap</td> <td nowrap> 10.15µs</td> <td nowrap> 10.09µs</td> <td nowrap> :white_circle: -0.42%</td> <td nowrap> 18.75µs</td> <td nowrap> 19.33µs</td> <td nowrap> :red_circle: 3.12%</td> <td nowrap> :yellow_circle: 92%</td></tr><tr><td><tt>execute/</tt><br><tt>regex_redux</td> <td nowrap> 455.62µs</td> <td nowrap> 458.07µs</td> <td nowrap> :white_circle: 0.91%</td> <td nowrap> 920.36µs</td> <td nowrap> 927.86µs</td> <td nowrap> :white_circle: 0.73%</td> <td nowrap> :red_circle: 103%</td></tr><tr><td><tt>execute/</tt><br><tt>rev_complement</td> <td nowrap> 425.84µs</td> <td nowrap> 419.87µs</td> <td nowrap> :green_circle: -1.64%</td> <td nowrap> 996.78µs</td> <td nowrap> 920.50µs</td> <td nowrap> :green_circle: -7.64%</td> <td nowrap> :red_circle: 119%</td></tr><tr><td><tt>execute/</tt><br><tt>tiny_keccak</td> <td nowrap> 325.03µs</td> <td nowrap> 326.12µs</td> <td nowrap> :white_circle: 0.10%</td> <td nowrap> 895.42µs</td> <td nowrap> 797.95µs</td> <td nowrap> :green_circle: -10.60%</td> <td nowrap> :red_circle: 145%</td></tr><tr><td><tt>execute/</tt><br><tt>trunc_f2i</td> <td nowrap> 732.22µs</td> <td nowrap> 747.73µs</td> <td nowrap> :red_circle: 2.19%</td> <td nowrap> 1.80ms</td> <td nowrap> 1.78ms</td> <td nowrap> :white_circle: -1.06%</td> <td nowrap> :red_circle: 138%</td></tr><tr><td><tt>instantiate/</tt><br><tt>wasm_kernel</td> <td nowrap> 54.36µs</td> <td nowrap> 54.90µs</td> <td nowrap> :white_circle: 1.02%</td> <td nowrap> 55.44µs</td> <td nowrap> 57.50µs</td> <td nowrap> :red_circle: 5.67%</td> <td nowrap> :green_circle: 5%</td></tr><tr><td><tt>translate/</tt><br><tt>erc1155</td> <td nowrap> 184.82µs</td> <td nowrap> 186.06µs</td> <td nowrap> :white_circle: 0.09%</td> <td nowrap> 315.35µs</td> <td nowrap> 309.68µs</td> <td nowrap> :green_circle: -1.63%</td> <td nowrap> :yellow_circle: 66%</td></tr><tr><td><tt>translate/</tt><br><tt>erc20</td> <td nowrap> 92.16µs</td> <td nowrap> 91.58µs</td> <td nowrap> :white_circle: -0.84%</td> <td nowrap> 154.12µs</td> <td nowrap> 151.60µs</td> <td nowrap> :green_circle: -1.82%</td> <td nowrap> :yellow_circle: 66%</td></tr><tr><td><tt>translate/</tt><br><tt>erc721</td> <td nowrap> 129.47µs</td> <td nowrap> 130.04µs</td> <td nowrap> :white_circle: 0.28%</td> <td nowrap> 220.62µs</td> <td nowrap> 217.96µs</td> <td nowrap> :white_circle: -1.07%</td> <td nowrap> :yellow_circle: 68%</td></tr><tr><td><tt>translate/</tt><br><tt>spidermonkey</td> <td nowrap> 57.53ms</td> <td nowrap> 57.68ms</td> <td nowrap> :white_circle: 0.25%</td> <td nowrap> 0.00ns</td> <td nowrap> 0.00ns</td> <td nowrap> :green_circle: -1.30%</td> <td nowrap> :green_circle: -100%</td></tr><tr><td><tt>translate/</tt><br><tt>wasm_kernel</td> <td nowrap> 4.00ms</td> <td nowrap> 4.02ms</td> <td nowrap> :white_circle: 0.56%</td> <td nowrap> 5.72ms</td> <td nowrap> 5.72ms</td> <td nowrap> :white_circle: 0.12%</td> <td nowrap> :green_circle: 42%</td></tr> </tbody> </table> 

 [Link to pipeline](https://gitlab.parity.io/parity/mirrors/wasmi/-/jobs/3253795)

**Comment by Robbepop** [comment]
Thanks a lot @behkod for this fix! Can you please fix the formatting (look into CI logs) so that we can merge this PR? :)

**Comment by behkod** [comment]
> Thanks a lot @behkod for this fix! Can you please fix the formatting (look into CI logs) so that we can merge this PR? :)

Oops, happened coz of automatic on-save formatting. just updated it. Thanks for quick review.

**Comment by behkod** [comment]
@Robbepop AFA concerns related to issue 735 & this pr, checks are passed (at least I guess so), but Clippy [raises a warning](https://github.com/paritytech/wasmi/actions/runs/5668752989/job/15362429532) on a file I didn't touch. Do you need me to change that as well or we are good to go?

**Comment by behkod** [comment]
Thanks for taking care fast & of course for the explanation.

**Pull request merged**
