### PR TITLE
refactor: impl ExtendInto and WrapInto for Self

### PR DESCRIPTION
**Pull request by yjhmelody**

### CODE REVIEW

**Comment by Robbepop** [comment]
What is the advantage of having ExtendInto compared to a simple From implementation?

**Comment by paritytech-cicd-pr** [comment]
## BENCHMARKS ## 

 <table> <thead> <tr> <th></th><th colspan=3>NATIVE</th><th colspan=3>WASMTIME</th><th></th> </tr> <tr> <th>BENCHMARK</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>MASTER</th><th>PR</th><th>DIFF</th><th>WASMTIME OVERHEAD</th> </tr> </thead> <tbody> <tr><td><tt>execute/</tt><br><tt>bare_call_0</td> <td nowrap> 1.27ms</td> <td nowrap> 1.27ms</td> <td nowrap> :white_circle: 0.25%</td> <td nowrap> 1.18ms</td> <td nowrap> 1.12ms</td> <td nowrap> :green_circle: -4.95%</td> <td nowrap> :green_circle: -12%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_0/typed</td> <td nowrap> 699.14µs</td> <td nowrap> 699.41µs</td> <td nowrap> :white_circle: 0.03%</td> <td nowrap> 583.43µs</td> <td nowrap> 545.39µs</td> <td nowrap> :green_circle: -6.56%</td> <td nowrap> :green_circle: -22%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_1</td> <td nowrap> 1.41ms</td> <td nowrap> 1.41ms</td> <td nowrap> :white_circle: 0.78%</td> <td nowrap> 1.49ms</td> <td nowrap> 1.38ms</td> <td nowrap> :green_circle: -7.35%</td> <td nowrap> :green_circle: -3%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_16</td> <td nowrap> 3.05ms</td> <td nowrap> 3.06ms</td> <td nowrap> :white_circle: -0.12%</td> <td nowrap> 5.06ms</td> <td nowrap> 4.99ms</td> <td nowrap> :green_circle: -1.37%</td> <td nowrap> :yellow_circle: 63%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_16/typed</td> <td nowrap> 1.32ms</td> <td nowrap> 1.35ms</td> <td nowrap> :white_circle: 1.81%</td> <td nowrap> 2.66ms</td> <td nowrap> 2.33ms</td> <td nowrap> :green_circle: -12.65%</td> <td nowrap> :yellow_circle: 73%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_1/typed</td> <td nowrap> 800.34µs</td> <td nowrap> 801.03µs</td> <td nowrap> :white_circle: 0.12%</td> <td nowrap> 875.59µs</td> <td nowrap> 872.93µs</td> <td nowrap> :white_circle: -0.31%</td> <td nowrap> :green_circle: 9%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_4</td> <td nowrap> 1.75ms</td> <td nowrap> 1.76ms</td> <td nowrap> :white_circle: 0.28%</td> <td nowrap> 2.15ms</td> <td nowrap> 2.18ms</td> <td nowrap> :red_circle: 1.26%</td> <td nowrap> :green_circle: 24%</td></tr><tr><td><tt>execute/</tt><br><tt>bare_call_4/typed</td> <td nowrap> 891.75µs</td> <td nowrap> 889.80µs</td> <td nowrap> :white_circle: -0.26%</td> <td nowrap> 1.00ms</td> <td nowrap> 995.12µs</td> <td nowrap> :white_circle: -0.76%</td> <td nowrap> :green_circle: 12%</td></tr><tr><td><tt>execute/</tt><br><tt>br_table</td> <td nowrap> 1.13ms</td> <td nowrap> 940.45µs</td> <td nowrap> :green_circle: -17.05%</td> <td nowrap> 1.14ms</td> <td nowrap> 1.14ms</td> <td nowrap> :white_circle: 0.11%</td> <td nowrap> :green_circle: 21%</td></tr><tr><td><tt>execute/</tt><br><tt>count_until</td> <td nowrap> 1.20ms</td> <td nowrap> 903.95µs</td> <td nowrap> :green_circle: -24.62%</td> <td nowrap> 2.40ms</td> <td nowrap> 2.78ms</td> <td nowrap> :red_circle: 15.72%</td> <td nowrap> :red_circle: 207%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial_iterative</td> <td nowrap> 365.04µs</td> <td nowrap> 365.40µs</td> <td nowrap> :white_circle: 0.12%</td> <td nowrap> 968.85µs</td> <td nowrap> 947.49µs</td> <td nowrap> :green_circle: -2.19%</td> <td nowrap> :red_circle: 159%</td></tr><tr><td><tt>execute/</tt><br><tt>factorial_recursive</td> <td nowrap> 722.92µs</td> <td nowrap> 757.45µs</td> <td nowrap> :red_circle: 4.67%</td> <td nowrap> 1.53ms</td> <td nowrap> 1.53ms</td> <td nowrap> :white_circle: 0.14%</td> <td nowrap> :red_circle: 103%</td></tr><tr><td><tt>execute/</tt><br><tt>fib_iterative</td> <td nowrap> 1.79ms</td> <td nowrap> 1.79ms</td> <td nowrap> :white_circle: 0.07%</td> <td nowrap> 5.00ms</td> <td nowrap> 5.01ms</td> <td nowrap> :white_circle: 0.09%</td> <td nowrap> :red_circle: 179%</td></tr><tr><td><tt>execute/</tt><br><tt>fib_recursive</td> <td nowrap> 7.19ms</td> <td nowrap> 7.13ms</td> <td nowrap> :white_circle: -0.79%</td> <td nowrap> 14.53ms</td> <td nowrap> 14.31ms</td> <td nowrap> :green_circle: -1.61%</td> <td nowrap> :red_circle: 101%</td></tr><tr><td><tt>execute/</tt><br><tt>global_bump</td> <td nowrap> 1.36ms</td> <td nowrap> 1.38ms</td> <td nowrap> :white_circle: 0.87%</td> <td nowrap> 3.67ms</td> <td nowrap> 3.66ms</td> <td nowrap> :white_circle: -0.10%</td> <td nowrap> :red_circle: 165%</td></tr><tr><td><tt>execute/</tt><br><tt>global_const</td> <td nowrap> 999.50µs</td> <td nowrap> 1.01ms</td> <td nowrap> :white_circle: 1.45%</td> <td nowrap> 2.84ms</td> <td nowrap> 2.84ms</td> <td nowrap> :white_circle: 0.09%</td> <td nowrap> :red_circle: 181%</td></tr><tr><td><tt>execute/</tt><br><tt>host_calls</td> <td nowrap> 32.64µs</td> <td nowrap> 32.78µs</td> <td nowrap> :white_circle: 0.42%</td> <td nowrap> 44.99µs</td> <td nowrap> 44.85µs</td> <td nowrap> :white_circle: -0.36%</td> <td nowrap> :green_circle: 37%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_fill</td> <td nowrap> 1.55ms</td> <td nowrap> 1.55ms</td> <td nowrap> :white_circle: -0.13%</td> <td nowrap> 4.21ms</td> <td nowrap> 4.21ms</td> <td nowrap> :white_circle: -0.03%</td> <td nowrap> :red_circle: 171%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_sum</td> <td nowrap> 1.55ms</td> <td nowrap> 1.55ms</td> <td nowrap> :white_circle: -0.03%</td> <td nowrap> 4.25ms</td> <td nowrap> 4.18ms</td> <td nowrap> :white_circle: -1.55%</td> <td nowrap> :red_circle: 170%</td></tr><tr><td><tt>execute/</tt><br><tt>memory_vec_add</td> <td nowrap> 3.09ms</td> <td nowrap> 3.08ms</td> <td nowrap> :white_circle: -0.39%</td> <td nowrap> 8.79ms</td> <td nowrap> 8.77ms</td> <td nowrap> :white_circle: -0.23%</td> <td nowrap> :red_circle: 185%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_is_even</td> <td nowrap> 1.30ms</td> <td nowrap> 1.30ms</td> <td nowrap> :white_circle: -0.13%</td> <td nowrap> 2.66ms</td> <td nowrap> 2.63ms</td> <td nowrap> :white_circle: -1.22%</td> <td nowrap> :red_circle: 103%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_ok</td> <td nowrap> 170.63µs</td> <td nowrap> 170.39µs</td> <td nowrap> :white_circle: -0.02%</td> <td nowrap> 359.96µs</td> <td nowrap> 359.88µs</td> <td nowrap> :white_circle: -0.05%</td> <td nowrap> :red_circle: 111%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_scan</td> <td nowrap> 214.56µs</td> <td nowrap> 213.92µs</td> <td nowrap> :white_circle: -0.20%</td> <td nowrap> 466.75µs</td> <td nowrap> 467.52µs</td> <td nowrap> :white_circle: 0.16%</td> <td nowrap> :red_circle: 119%</td></tr><tr><td><tt>execute/</tt><br><tt>recursive_trap</td> <td nowrap> 16.84µs</td> <td nowrap> 16.87µs</td> <td nowrap> :white_circle: -0.02%</td> <td nowrap> 36.06µs</td> <td nowrap> 36.46µs</td> <td nowrap> :white_circle: 1.30%</td> <td nowrap> :red_circle: 116%</td></tr><tr><td><tt>execute/</tt><br><tt>regex_redux</td> <td nowrap> 662.95µs</td> <td nowrap> 661.36µs</td> <td nowrap> :white_circle: -0.12%</td> <td nowrap> 1.60ms</td> <td nowrap> 1.63ms</td> <td nowrap> :red_circle: 1.48%</td> <td nowrap> :red_circle: 146%</td></tr><tr><td><tt>execute/</tt><br><tt>rev_complement</td> <td nowrap> 593.42µs</td> <td nowrap> 589.72µs</td> <td nowrap> :white_circle: -0.81%</td> <td nowrap> 1.56ms</td> <td nowrap> 1.55ms</td> <td nowrap> :white_circle: -0.23%</td> <td nowrap> :red_circle: 164%</td></tr><tr><td><tt>execute/</tt><br><tt>tiny_keccak</td> <td nowrap> 466.67µs</td> <td nowrap> 462.57µs</td> <td nowrap> :white_circle: 0.13%</td> <td nowrap> 1.37ms</td> <td nowrap> 1.38ms</td> <td nowrap> :white_circle: 1.23%</td> <td nowrap> :red_circle: 199%</td></tr><tr><td><tt>execute/</tt><br><tt>trunc_f2i</td> <td nowrap> 1.08ms</td> <td nowrap> 1.08ms</td> <td nowrap> :white_circle: -0.07%</td> <td nowrap> 2.68ms</td> <td nowrap> 2.66ms</td> <td nowrap> :white_circle: -0.53%</td> <td nowrap> :red_circle: 146%</td></tr><tr><td><tt>instantiate/</tt><br><tt>wasm_kernel</td> <td nowrap> 67.91µs</td> <td nowrap> 68.91µs</td> <td nowrap> :white_circle: 3.01%</td> <td nowrap> 92.63µs</td> <td nowrap> 92.44µs</td> <td nowrap> :white_circle: -0.39%</td> <td nowrap> :green_circle: 34%</td></tr><tr><td><tt>translate/</tt><br><tt>wasm_kernel</td> <td nowrap> 4.16ms</td> <td nowrap> 4.16ms</td> <td nowrap> :white_circle: -0.23%</td> <td nowrap> 7.81ms</td> <td nowrap> 7.81ms</td> <td nowrap> :white_circle: 0.16%</td> <td nowrap> :yellow_circle: 88%</td></tr> </tbody> </table> 

 [Link to pipeline](https://gitlab.parity.io/parity/mirrors/wasmi/-/jobs/1991599)

**Comment by yjhmelody** [comment]
> What is the advantage of having ExtendInto compared to a simple From implementation?

Maybe `From/Into` is too loosely constraint for these types?
I only add the wasm supported type for reducing code.

**Comment by yjhmelody** [comment]
@Robbepop  BTW, such as these impls are not used, since wasmi do not directly use f32/f64.
```rust
impl_extend_into!(i64, f64);
impl_extend_into!(u64, f64);
impl_extend_into!(f32, f64);
```

**Comment by Robbepop** [comment]
> > What is the advantage of having ExtendInto compared to a simple From implementation?
> 
> Maybe `From/Into` is too loosely constraint for these types? I only add the wasm supported type for reducing code.
> 
> I think that these trait implementations are only for one-to-one correspondence with wasm instructions, so I do so reasonably. Just like `impl_transmute_into_self`

Yeah I just saw that. Was looking at this PR from mobile and didn't get the code on the small format.

**Comment by Robbepop** [comment]
> @Robbepop BTW, such as these impls are not used, since wasmi do not directly use f32/f64.
> 
> ```rust
> impl_extend_into!(i64, f64);
> impl_extend_into!(u64, f64);
> impl_extend_into!(f32, f64);
> ```

I think it makes sense to remove those impls. Generally there never was a clear design behind when to use `f32/f64` and their `F32/F64` counterparts in `wasmi` but I think it would make sense to just always use `F32/F64` everywhere.

**Comment by Robbepop** [comment]
Renamed the PR since this does not implement any new feature but acts more like a refactoring of code.

**Review by Robbepop — APPROVED** [review]
LGTM

**Comment by Robbepop** [comment]
I think this kind of generalization of load/store operations is a step forward.

**Pull request merged**
