### PR TITLE
Forward parity-wasm's feature 'reduced-stack-buffer'

### PR DESCRIPTION
**Pull request by ithinuel**
This PR introduces a new feature as a forward of underlying feature introduced in https://github.com/paritytech/parity-wasm/pull/283.

### CODE REVIEW

**Review by coriolinus — APPROVED** [review]

**Comment by ithinuel** [comment]
Update: paritytech/parity-wasm#283 has been merged.

This PR will be rebased with a bump to parity-wasm version once a new one is released.

**Comment by jiayihu** [comment]
I think `parity-wasm` should also be updated to `0.42.1` right?

**Comment by pepyakin** [comment]
I am actually not sure if it's that version. Not even sure it's released. @athei have you made a release that includes https://github.com/paritytech/parity-wasm/pull/283 ?

**Comment by athei** [comment]
> I am actually not sure if it's that version. Not even sure it's released. @athei have you made a release that includes [paritytech/parity-wasm#283](https://github.com/paritytech/parity-wasm/pull/283) ?

No. Those changes are unreleased. I will do a release.

**Comment by athei** [comment]
> Update: [paritytech/parity-wasm#283](https://github.com/paritytech/parity-wasm/pull/283) has been merged.
> 
> This PR will be rebased with a bump to parity-wasm version once a new one is released.

I just released the changes as `v.42.2`.

**Comment by ithinuel** [comment]
The last step before this PR can be merge-able is to bump `wasmi` to v0.42.2.
It requires the changes proposed by @jiayihu in https://github.com/paritytech/wasmi/commit/f7235e13583d34749910abfd7a31fe9855228a33 as part of the now closed PR https://github.com/paritytech/wasmi/pull/239.

Those changes aren't directly related to the `reduced-stack-buffer` feature so you may want to see a dedicated PR for the bump before considering this PR.
Let me know what you think is the most appropriate.

**Comment by athei** [comment]
Please open another PR where you bump `parity-wasm`.

**Comment by ithinuel** [comment]
PR created here: https://github.com/paritytech/wasmi/pull/251

**Review by athei — APPROVED** [review]

**Comment by stevemk14ebr** [comment]
Can this please be merged

**Review by pepyakin — APPROVED** [review]

**Pull request merged**
